[package]
name = "streamsplit"
version = "0.1.0"
authors = ["Jan Kanis <jan.code@jankanis.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
once_cell = "1.7"
hex = "0.4"